---
- name: Configure Db
  hosts: all
  become: true

  tasks:
    - name: Add an apt key by id from a keyserver
      apt_key:
        keyserver: hkp://keyserver.ubuntu.com:80
        id: EA312927

    - name: Add specified repository into sources list.
      apt_repository:
        repo: deb http://repo.mongodb.org/apt/ubuntu xenial/mongodb-org/3.2 multiverse


    - name: Update repositories cache and install mongodb
      apt:
        name: "{{ item }}"
        update_cache: yes
      with_items:
        - mongodb-org

    - name: enable mongodb
      systemd:
        name: mongod
        state: restarted
        enabled: yes
